### ISSUE TITLE
Test problems with fixes

### ISSUE THREAD

**Issue by dstango** [sproket/Persism#14]
I tried to build the project (LocalDB only) and encountered two problems:

1. A localization issue in TestH2
2. Implicit javafx-dependency, which is actually not needed

Here come two patches:

**Localization issue in TestH2**

The localization issue occurs because I'm in Germany and getMessage() contains both a localized version of the error message plus the original message in English. The proposed fix is to change the test from "startsWith" to "contains". This fixes it for me, though it would probably be better to check for some well defined specific exception or error code -- yet that would require more digging into H2, so I didn't do that.
```
diff --git a/test/net/sf/persism/TestH2.java b/test/net/sf/persism/TestH2.java
index 9281c3c..c55b5db 100644
--- a/test/net/sf/persism/TestH2.java
+++ b/test/net/sf/persism/TestH2.java
@@ -514,2 +514,2 @@
-            assertTrue("message starts with 'Unique index or primary key violation'",
-                    e.getMessage().startsWith("Unique index or primary key violation"));
+            assertTrue("message contains 'Unique index or primary key violation' failed: "+e.getMessage(),
+                    e.getMessage().contains("Unique index or primary key violation"));
```
 
**Implicit javafx-dependency, which is actually not needed**

Javafx has been removed from the jdk, and even my zulu-8 doesn't bring it out of the box. And it's usage doesn't seem to be nescessary at all, at the same can be achieved with ImageIO.
```
diff --git a/test/net/sf/persism/dao/northwind/Category.java b/test/net/sf/persism/dao/northwind/Category.java
index 7f08af1..c1c5623 100644
--- a/test/net/sf/persism/dao/northwind/Category.java
+++ b/test/net/sf/persism/dao/northwind/Category.java
@@ -3,2 +2,0 @@
-import javafx.embed.swing.SwingFXUtils;
-import javafx.scene.image.Image;
@@ -11,0 +10 @@
+import javax.imageio.ImageIO;
@@ -85,2 +84 @@
-                Image image1 = new Image(in);
-                image = SwingFXUtils.fromFXImage(image1, null);
+                image = ImageIO.read(in);
```

I could also try to provide a pull request, if you like, though that would be my first try with github forking ... ;-) 

On a side note: is there a special reason, why you put all the local databases into the user-home directory? I'd rather propose to have them local to the project, most likely somewhere in target.

**Comment by sproket** [comment]
Yeah the image one is for testing Binary types. The Northwind DB has a BMP photo in there.  Thanks!
