### ISSUE TITLE
Is there any easier option to update an object in a "one-to-many" relationship?

### ISSUE THREAD

**Issue by vicenrico** [sproket/Persism#36]
Hello, how can I easily update an object belonging to a one-to-many relationship?. I mean:
```

Table Movies(id, title, ...)
Table Genres(id, movie_id, name)
```

I have, movie Blade runner and a list of genres( scifi, action...). What I'm doing is delete the genres and again insert the new ones, but I remember years ago I was using ormlite and they had something like 'movie.getGenres.update(...)'
Is there something similiar to this for persism? Am I using the best and most efficient way to update a register in a one-to-many relationship? There will be an easier feature to update 'children' records in this kind of relationships?

By the way, I'm using sqlite as DB Engine

**Comment by sproket** [comment]
I don't have anything specific for that. Usually I take the data from the DB and compare to the data being submitted to decide what to insert/update or delete.  Maybe if I think of a generalized way to do this I can add it as a feature.  Thanks!
