### ISSUE TITLE
Maybe the method Types.isCountable is wrong?

### ISSUE THREAD

**Issue by pablogrisafi1975** [sproket/Persism#5]
**Describe the bug**
Maybe the method Types.isCountable is wrong?

The code is :

        public boolean isCountable() {
            return this == IntegerType || this == integerType || this == LongType || this == longType || this == byteType || this == ByteType
                    || this == ShortType || this == shortType || this == DoubleType || this == doubleType || this == BigDecimalType;
        }

DoubleType, doubleType and BigDecimalType seem to be included by mistake , and BigInteger seems to be missing.

Of course, maybe you have your reasons, but in that case please write them.

Thanks for this project! Great idea and compact implementation!

**Comment by sproket** [comment]
Thanks! Yeah, this method is too vague. It's only used to test if you map an autoinc to something sensible. Now I realize that it's kind of silly anyway. Autoinc to Byte? I'll fix this - it should really only test for long or integer.  Those are the only sensible mappings.

> Thanks for this project! Great idea and compact implementation!

Thanks. Please star it. Maybe it can trend eventually. :)

**Comment by pablogrisafi1975** [comment]
BigInteger should be possible too.
I suggest changing the name to something more descriptive

Starred!

**Comment by sproket** [comment]
It only makes sense to have auto-inc as long or int so I clarified the method name and the logged text. See next release.
